services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "cd app/ &&
                gunicorn base.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/backend/app/staticfiles
    env_file:
      - ./config/.env/env.prod
    depends_on:
      - db
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/db/database-env.prod
  nginx:
    build: ./config/nginx/.
    volumes:
      - static_volume:/home/app/backend/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
