version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "cd app/ &&
                gunicorn base.wsgi:application --workers=4 --timeout 120 --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/backend/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./config/.env/env.prod
  redis:
    image: redis:alpine
  nginx:
    build:
      context: ./config/nginx/
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/backend/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
