# Generated by Django 4.1.5 on 2023-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0003_season_episode'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_medias',
            field=models.ManyToManyField(blank=True, related_name='users', to='whatchlists.media'),
        ),
    ]
