# Generated by Django 4.1.7 on 2023-02-16 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_rename_seasons_season_episodes'),
        ('users', '0002_userprofile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='media', to='watchlists.media'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
