# Generated by Django 4.1.5 on 2023-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0006_rename_omdb_id_movie_imdb_id_and_more'),
        ('users', '0002_alter_user_options_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='whatchlists.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_series',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='whatchlists.series'),
        ),
    ]
