# Generated by Django 4.1.5 on 2023-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0007_rename_episode_num_episode_episode_numb_and_more'),
        ('users', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='whatchlists.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_series',
            field=models.ManyToManyField(blank=True, related_name='users', to='whatchlists.series'),
        ),
    ]
