# Generated by Django 4.1.5 on 2023-02-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='seasons',
            new_name='episodes',
        ),
    ]
