# Generated by Django 4.1.5 on 2023-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='last_retrieved',
            field=models.DateField(auto_now=True),
        ),
    ]
