# Generated by Django 4.1.5 on 2023-01-27 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_reviewlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(through='reviews.ReviewLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
