# Generated by Django 4.1.5 on 2023-02-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_user_alter_reviewlikes_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
