# Generated by Django 4.1.5 on 2023-02-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
