# Generated by Django 4.1.5 on 2023-02-06 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('released', models.DateField(verbose_name='Release date')),
                ('genres', models.CharField(max_length=255)),
                ('poster', models.URLField()),
                ('imdb_id', models.CharField(max_length=50)),
                ('imdb_rating', models.FloatField()),
                ('media_type', models.CharField(choices=[('MOVIE', 'Movie'), ('SERIES', 'Series')], max_length=6)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('total_seasons', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, help_text='Use such format: 2018-2022', max_length=9, null=True)),
            ],
        ),
    ]
