# Generated by Django 4.1.5 on 2023-01-28 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('released', models.DateField()),
                ('episode_num', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
                ('plot', models.TextField()),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('year', models.CharField(help_text='Use such format: 2018-2022', max_length=9)),
                ('released', models.DateField(verbose_name='Release date')),
                ('plot', models.TextField()),
                ('total_seasons', models.PositiveIntegerField()),
                ('genres', models.ManyToManyField(related_name='series', to='whatchlists.genre')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('season', models.PositiveIntegerField()),
                ('total_episodes', models.PositiveIntegerField()),
                ('episodes', models.ManyToManyField(related_name='season', to='whatchlists.episode')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='whatchlists.series')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
    ]
