# Generated by Django 4.1.5 on 2023-02-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatchlists.media',),
        ),
        migrations.CreateModel(
            name='SeriesProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatchlists.media',),
        ),
    ]
