# Generated by Django 4.1.5 on 2023-01-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0002_episode_series_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'EpisodeTest', 'verbose_name_plural': 'EpisodesTest'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'SeasonTest', 'verbose_name_plural': 'SeasonsTest'},
        ),
        migrations.RemoveField(
            model_name='season',
            name='episodes',
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whatchlists.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatchlists.series'),
        ),
    ]
