# Generated by Django 4.1.5 on 2023-01-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0003_alter_episode_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
