# Generated by Django 4.1.5 on 2023-02-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0003_season_episode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieProxy',
        ),
        migrations.DeleteModel(
            name='SeriesProxy',
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatchlists.media',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatchlists.media',),
        ),
    ]
