# Generated by Django 4.1.5 on 2023-02-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0004_delete_movieproxy_delete_seriesproxy_movie_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='plot',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
