# Generated by Django 4.1.5 on 2023-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0004_alter_episode_options_alter_season_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='omdb_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='omdb_id',
            field=models.CharField(default='tt', max_length=50),
            preserve_default=False,
        ),
    ]
