# Generated by Django 4.1.5 on 2023-01-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0005_movie_omdb_id_series_omdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='omdb_id',
            new_name='imdb_id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='omdb_id',
            new_name='imdb_id',
        ),
    ]
