# Generated by Django 4.1.5 on 2023-01-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0006_rename_omdb_id_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode_num',
            new_name='episode_numb',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='season_numb',
        ),
    ]
