# Generated by Django 4.1.5 on 2023-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0007_rename_episode_num_episode_episode_numb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
