# Generated by Django 4.1.5 on 2023-02-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0010_alter_episode_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='whatchlists.series'),
        ),
    ]
