# Generated by Django 4.1.5 on 2023-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatchlists', '0012_alter_episode_season_alter_season_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='poster',
            field=models.URLField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='www.youtube.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='poster',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
