on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: development
    env:
      DEBUG: ${{ vars.DEBUG }}
      SECRET_KEY: ${{ vars.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
      SQL_ENGINE: ${{ vars.SQL_ENGINE }}
      SQL_DATABASE: ${{ vars.SQL_DATABASE }}
      SQL_USER: ${{ vars.SQL_USER }}
      SQL_PASSWORD: ${{ vars.SQL_PASSWORD }}
      SQL_HOST: ${{ vars.SQL_HOST }}
      SQL_PORT: ${{ vars.SQL_PORT }}
      DATABASE: ${{ vars.DATABASE }}
      API_KEY: ${{ vars.API_KEY }}
      CORS_ALLOWED_ORIGINS: ${{ vars.CORS_ALLOWED_ORIGINS }}
      INTERNAL_IPS: ${{ vars.INTERNAL_IPS }}
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}
      PYTHONPATH: ${{ vars.PYTHONPATH }}
      REDIS_HOST: ${{ vars.REDIS_HOST }}
    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_DB: codingvalley
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: run linter and tests
        run: |
          . venv/bin/activate
          flake8 --statistics app
          pytest -v app
